### ISSUE TITLE
Create binaries without running tests

### ISSUE THREAD

**Issue by richfitz** [r-hub/rhub-backend#16] opened 2016-10-26 08:51 UTC
This would be super useful, and I think is one of the main reasons people use win builder (or at least it has been for me).  It will tend to be far quicker than running all tests.  Main use case here is packages that contain compiled code.

**Comment by gaborcsardi** [comment] 2016-10-26 08:51
:+1:

**Comment by gaborcsardi** [comment] 2016-11-14 12:04
Essentially a duplicate of #3, I believe. To build the binary, we just need to install, and then zip up the installed package.

**Closed as completed by gaborcsardi** 2016-11-14 12:04 UTC
